export const MOVIE_SHORT_DURATION = 40;

export const MOBILE_SCREEN_LIMIT = 767;
export const TABLET_SCREEN_LIMIT = 989;
export const INTERIM_SCREEN_LIMIT = 1279;

export const MOBILE_INITIAL_MOVIES_NUMBER = 5;
export const TABLET_INITIAL_MOVIES_NUMBER = 8;
export const INTERIM_INITIAL_MOVIES_NUMBER = 12;
export const DESKTOP_INITIAL_MOVIES_NUMBER = 16;

export const MOBILE_ADDITIONAL_MOVIES_NUMBER = 2;
export const TABLET_ADDITIONAL_MOVIES_NUMBER = 2;
export const INTERIM_ADDITIONAL_MOVIES_NUMBER = 3;
export const DESKTOP_ADDITIONAL_MOVIES_NUMBER = 4;
